### PR TITLE
Update example to make it work with webpack 2

### PR DESCRIPTION
**Pull request by gmarziou**
Hello, here is what I had to change to run the example with webpack 2.2

### CODE REVIEW

**Comment by tettusud** [comment]
Thank you @gmarziou for trying the plugin, I have updated the webpack version in package.json,however irrespective of webpack version this plugin should be working.
I appreciate your feedback.

**Comment by gmarziou** [comment]
I'm surprised you could keep `debug: true,` with webpack 2, for me it was failing and this is why I added:

```
       new webpack.LoaderOptionsPlugin({
             debug: true
        }),
```

**Comment by tettus** [comment]
Hi @gmarziou  ,apologies I think I missed to commit that change.I will do it today.Thank you

**Comment by tettusud** [comment]
Hi @gmarziou  apologies, I missed to commit that change, I will update it today.

**Comment by gmarziou** [comment]
:)

**Pull request closed without merging**
